FROM adoptopenjdk/openjdk17
COPY vuelosudea-0.0.1-SNAPSHOT.jar /usr/src/bootdocker/vuelosudea-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src/bootdocker
EXPOSE 8089
ENTRYPOINT ["java", "-jar", "/usr/src/bootdocker/vuelosudea-0.0.1-SNAPSHOT.jar"]